### ISSUE TITLE
API to ingest candidate URLs

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#119]
```[tasklist]
### Tasks
- [x] API that takes a post request with a URL, title and collection_id and creates a candidate URL based on that.
- [x] Batch create candidate URL to prevent tens of thousands of API calls for a single collection
- [x] What is the max data that can be passed for the batch create?
- [x] Script that integrates with the candidate URL generator and calls the API from the test server
```
