### ISSUE TITLE
EPIC: Collection lifecycle with tracking of each stage

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#124]
```[tasklist]
### Initial Cleanup
- [ ] WEB APP: Figure out what we need from a given collection and add some Required URLs
- [ ] TEST SERVER: A collection has been indexed and the initial XML + candidate URLs are ready on the test server
- [ ] TEST SERVER: The candidate URLs for this collection have been uploaded to S3
- [ ] WEB APP: The web app has consumed these candidate URLs
- [ ] WEB APP: The initial cleaning of the candidate URLs has been completed
- [ ] WEB APP: The web app has pushed the cleaned config file back to git
- [ ] GITHUB: The config files have been merged and the updated config file is now on the test server
- [ ] TEST SERVER: The collection on the test server has been reindexed
- [ ] TEST SERVER: A quality check has been performed to make sure all rules are correctly applied
- [ ] PRODUCTION SERVER: All collections have been pushed to production
- [ ] PRODUCTION SERVER: A final quality check on production has been performed.
```

```[tasklist]
### Ongoing Maintenance
- [ ] A job on the test server has reindexed the collection, bringing in new URLs
- [ ] The test server has automatically updated new URLs on the S3 bucket and notified the ingesting helper web app
- [ ] The web app has ingested these new URLs and notified curators to go look at new URLs received from the test server
- [ ] Cleanup on new URLs has been completed
- [ ] New XML file pushed to git, merged, and test server reindexed
- [ ] Push to production and quality check
```
