### ISSUE TITLE
Make the status column on the collections list filterable

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#158]
Currently the division column is filterable

![image](https://github.com/NASA-IMPACT/sde-indexing-helper/assets/4883631/858227b0-9af5-4b60-85c7-34c179ef5f15)

This is done by using [this code](https://github.com/NASA-IMPACT/sde-indexing-helper/blob/dev/sde_indexing_helper/static/js/collection_list.js#L34-L52).

We need the status column to be filterable in a similar way. The hurdle here is that status has elements that are not just text (the button dropdown etc). Therefore, the same piece of code does not work. 

```[tasklist]
### Tasks
- [ ] Remove the code for filtering column 8
- [ ] Copy over the filtering code for column 3 for column 6 (status)
- [ ] Instead of using `column.data.unique` figure out a way to use `curation_status_list` being passed in from the context
- [ ] When a user selects an option, filter based on the text inside the `<button>` tag
- [ ] Make the filtering code work inside `column.search` (lines 43, 44)
```
