### ISSUE TITLE
Be able to match documents with a NOT condition

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#209]
For example, documents that do NOT end in `*.pdf`

```[tasklist]
### Tasks
- [ ] Backend changes to allow for the NOT filter
- [ ] Frontend changes to allow for the NOT filter
- [ ] Sinequa function for the NOT filter integrated into the pipeline
```
