### ISSUE TITLE
Deal with collections that don't have a Sinequa configuration

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#254]
```[tasklist]
### Tasks
- [x] Identify collections that don't have a config folder
- [ ] Make them visible on the web app
- [ ] Get guidance from SMEs on one of two actions: Delete, or Keep
- [ ] Filter for "Delete/Combine" from the collection list
- [ ] Add an ability to hide these collections on the web app
```
