### ISSUE TITLE
GitHub pipeline shows 0 files changed even with rules present

### ISSUE THREAD

**Issue by code-geek** [NASA-IMPACT/sde-indexing-helper#269]
```[tasklist]
### Tasks
- [ ] Write a management command that can be run as a backup to the current frontend/celery
- [ ] Debug pipeline locally to see if rules are being incorporated
- [ ] Debug the part that updates content on GitHub
- [ ] Make sure rules haven't already been merged
- [ ] Write a condition that doesn't make a commit if rules are the same?
- [ ] Investigate why the pipeline fails when a lot of collections are pushed at once
- [ ] Investigate if we can use celery to avoid timeout
```
