### ISSUE TITLE
Integrate Treeroot into complete process

### ISSUE THREAD

**Issue by CarsonDavis** [NASA-IMPACT/sde-indexing-helper#279]
## Overview
We want to add treeroots to the governance process. 
### Config is made from within webapp
- treeroot is typed from the beginning (datamodels needs to supply a blank value for default?)
- treeroot is editable after this
- generated configs have the treeroot

### Config is imported
- Treeroot is scraped from config at import
- Treeroot is editable after this from frontend
- generated configs have the treeroot

```[tasklist]
### Tasks
- [ ] double check the datamodels default behavior
- [ ] code that allows treeroot to be edited on the frontend
- [ ] code that allows generation to use the frontend treeroot value
- [ ] a final step where the webapp values are updated against the current config values before moving forwards and allowing edits
```
