### ISSUE TITLE
Strengthen the curation communication pipeline through notifications

### ISSUE THREAD

**Issue by bishwaspraveen** [NASA-IMPACT/sde-indexing-helper#621]
## Description
Communication in the curation process has been hard to keep up on our project. So, to solve this, there is a need to automate this communication process throughout the communication pipeline. There are three major steps to be executed : 

- When the curators decide to bring in a new collection, they explore a website and make notes about it. They bring in the notes and create a collection on the webapp with basic info about the collection. This has to be notified to the collection engineering personnel. There is a need to automate this process.
- When the collection engineer works on the source and is done, he gets on the webapp, imports the urls into the webapp using the dev server API endpoint and at this point the curator needs to be told that the source is ready for curation. Here comes another need to automate this process.
- When the curator is done curating, they mark the source as curated and now the source is ready to go into test. The dev team needs to be communicated about this. This is another process that can be automated.

```[tasklist]
### Tasks
- [x] Notify Li when a new source is discovered and needs to be engineered
- [ ] https://github.com/NASA-IMPACT/sde-indexing-helper/issues/622
- [ ] https://github.com/NASA-IMPACT/sde-indexing-helper/issues/623
```
